# As of: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
ZonesList = [
    ['UTC', 'UTC', 'Etc/UTC'],
    ['Exchange', 'Exchange', 'Atlantic/Reykjavik'],
    ['UTC-10:00', 'Honolulu', 'Pacific/Honolulu'],
    ['UTC-08:00', 'Juneau', 'America/Juneau'],
    ['UTC-07:00', 'Los Angeles', 'America/Los_Angeles'],
    ['UTC-07:00', 'Phoenix', 'America/Phoenix'],
    ['UTC-07:00', 'Vancouver', 'America/Vancouver'],
    ['UTC-06:00', 'Denver', 'America/Denver'],
    ['UTC-06:00', 'San Salvador', 'America/El_Salvador'],
    ['UTC-05:00', 'Bogota', 'America/Bogota'],
    ['UTC-05:00', 'Chicago', 'America/Chicago'],
    ['UTC-05:00', 'Lima', 'America/Lima'],
    ['UTC-05:00', 'Mexico City', 'America/Mexico_City'],
    ['UTC-04:00', 'Caracas', 'America/Caracas'],
    ['UTC-04:00', 'New York', 'America/New_York'],
    ['UTC-04:00', 'Santiago', 'America/Santiago'],
    ['UTC-04:00', 'Toronto', 'America/Toronto'],
    ['UTC-03:00', 'Buenos Aires', 'America/Buenos_Aires'],
    ['UTC-03:00', 'Sao Paulo', 'America/Sao_Paulo'],
    ['UTC-00:00', 'Reykjavik', 'Atlantic/Reykjavik'],
    ['UTC+01:00', 'Lagos', 'Africa/Lagos'],
    ['UTC+01:00', 'London', 'Europe/London'],
    ['UTC+02:00', 'Belgrade', 'Europe/Belgrade'],
    ['UTC+02:00', 'Berlin', 'Europe/Berlin'],
    ['UTC+02:00', 'Cairo', 'Africa/Cairo'],
    ['UTC+02:00', 'Copenhagen', 'Europe/Copenhagen'],
    ['UTC+02:00', 'Johannesbourg', 'Africa/Johannesburg'],
    ['UTC+02:00', 'Luxembourg', 'Europe/Luxembourg'],
    ['UTC+02:00', 'Madrid', 'Europe/Madrid'],
    ['UTC+02:00', 'Oslo', 'Europe/Oslo'],
    ['UTC+02:00', 'Paris', 'Europe/Paris'],
    ['UTC+02:00', 'Rome', 'Europe/Rome'],
    ['UTC+02:00', 'Stockholm', 'Europe/Stockholm'],
    ['UTC+02:00', 'Warsaw', 'Europe/Warsaw'],
    ['UTC+02:00', 'Zurich', 'Europe/Zurich'],
    ['UTC+03:00', 'Athens', 'Europe/Athens'],
    ['UTC+03:00', 'Bahrain', 'Asia/Bahrain'],
    ['UTC+03:00', 'Helsinki', 'Europe/Helsinki'],
    ['UTC+03:00', 'Istanbul', 'Europe/Istanbul'],
    ['UTC+03:00', 'Jerusalem', 'Asia/Jerusalem'],
    ['UTC+03:00', 'Kuwait', 'Asia/Kuwait'],
    ['UTC+03:00', 'Moscow', 'Europe/Moscow'],
    ['UTC+03:00', 'Qatar', 'Asia/Qatar'],
    ['UTC+03:00', 'Riga', 'Europe/Riga'],
    ['UTC+03:00', 'Riyadh', 'Asia/Riyadh'],
    ['UTC+03:00', 'Tallinn', 'Europe/Tallinn'],
    ['UTC+03:00', 'Vilnius', 'Europe/Vilnius'],
    ['UTC+04:00', 'Dubai', 'Asia/Dubai'],
    ['UTC+04:00', 'Muscat', 'Asia/Muscat'],
    ['UTC+04:30', 'Tehran', 'Asia/Tehran'],
    ['UTC+05:00', 'Ashkhabad', 'Asia/Ashkhabad'],
    ['UTC+05:30', 'Kolkata', 'Asia/Kolkata'],
    ['UTC+06:00', 'Almaty', 'Asia/Almaty'],
    ['UTC+07:00', 'Bangkok', 'Asia/Bangkok'],
    ['UTC+07:00', 'Ho Chi Minh', 'Asia/Ho_Chi_Minh'],
    ['UTC+07:00', 'Jakarta', 'Asia/Jakarta'],
    ['UTC+08:00', 'Chongqing', 'Asia/Chongqing'],
    ['UTC+08:00', 'Hong Kong', 'Asia/Hong_Kong'],
    ['UTC+08:00', 'Perth', 'Australia/Perth'],
    ['UTC+08:00', 'Shanghai', 'Asia/Shanghai'],
    ['UTC+08:00', 'Singapore', 'Asia/Singapore'],
    ['UTC+08:00', 'Taipei', 'Asia/Taipei'],
    ['UTC+09:00', 'Seoul', 'Asia/Seoul'],
    ['UTC+09:00', 'Tokyo', 'Asia/Tokyo'],
    ['UTC+09:30', 'Adelaide', 'Australia/Adelaide'],
    ['UTC+10:00', 'Brisbane', 'Australia/Brisbane'],
    ['UTC+10:00', 'Sydney', 'Australia/Sydney'],
    ['UTC+11:00', 'Norfolk Island', 'Pacific/Norfolk'],
    ['UTC+12:00', 'New Zealand', 'Etc/GMT-13'],
    ['UTC+12:45', 'Chatham Islands', 'Pacific/Chatham'],
    ['UTC+13:00', 'Tokelau', 'Etc/GMT-13']
]

# vim: ts=4 ft=python nowrap fdm=marker
